export const fieldNames: Record<string, string> = {
  // Personal Information
  fullName: "Full Name",
  dob: "Date of Birth",
  citizenship: "Citizenship",
  maritalStatus: "Marital Status",
  phone: "Phone Number",
  email: "Email",
  street: "Street Address",
  city: "City",
  state: "State",
  zip: "ZIP Code",
  residencyYears: "Years at Residence",
  residencyMonths: "Months at Residence",
  housingType: "Housing Type",
  monthlyPayment: "Monthly Housing Payment",
  previousAddress: "Previous Address",

  // Employment Information
  isUnemployed: "Unemployed",
  employerName: "Employer Name",
  employerPhone: "Employer Phone",
  employerStreet: "Employer Street",
  employerUnit: "Employer Unit",
  employerCity: "Employer City",
  employerState: "Employer State",
  employerZip: "Employer ZIP",
  employerCountry: "Employer Country",
  position: "Job Position",
  startDate: "Start Date",
  yearsInLineOfWork: "Years in Line of Work",
  monthsInLineOfWork: "Months in Line of Work",
  isSelfEmployed: "Self-Employed",
  isEmployedByFamily: "Employed by Family",
  ownershipShare: "Ownership Share (%)",
  monthlyIncomeBase: "Base Monthly Income",
  monthlyIncomeOvertime: "Overtime Income",
  monthlyIncomeBonus: "Bonus Income",
  monthlyIncomeCommission: "Commission Income",
  monthlyIncomeMilitary: "Military Pay",
  monthlyIncomeOther: "Other Monthly Income",
  otherIncome: "Other Income Details",

  // Assets & Liabilities
  assetsAccounts: "Asset Accounts",
  otherAssets: "Other Assets",
  liabilities: "Liabilities",
  otherLiabilities: "Other Liabilities",

  // Real Estate Information
  ownsRealEstate: "Owns Real Estate",
  properties: "Properties",

  // Loan Property Information
  underContract: "Under Contract",
  salesPrice: "Sales Price",
  downPayment: "Down Payment",
  propertyAddress: "Property Address",
  occupancy: "Occupancy Type",
  receivingGift: "Receiving Gift Funds",
  giftAssetType: "Gift Asset Type",
  giftDeposited: "Gift Deposited?",
  giftSource: "Gift Source",
  giftValue: "Gift Amount",

  // Declarations
  occupyAsPrimary: "Will Occupy as Primary Residence",
  ownedPropertyLast3Years: "Owned Property in Last 3 Years",
  typeOfProperty: "Type of Property",
  titleHeld: "Title Held",
  relationshipWithSeller: "Relationship with Seller",
  borrowingMoney: "Borrowing Money",
  borrowingMoneyAmount: "Borrowing Money Amount",
  mortgageOnOtherProperty: "Mortgage on Other Property",
  obligatedOnLoan: "Obligated on a Loan",
  cosigner: "Cosigner",
  borrowedDownPayment: "Borrowed Down Payment",
  declaredForeclosure: "Declared Foreclosure",
  declaredBankruptcy: "Declared Bankruptcy",
  bankruptcyTypes: "Bankruptcy Types",
};
